# Generated by Django 2.1.7 on 2019-03-30 22:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('latitude', models.CharField(max_length=32)),
                ('longitude', models.CharField(max_length=32)),
                ('geohash', models.CharField(max_length=16)),
                ('coords_json', models.TextField()),
                ('location_name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Spotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.CharField(max_length=128)),
                ('fb_id', models.CharField(max_length=128)),
                ('fb_json', models.TextField()),
                ('fb_access_token', models.CharField(max_length=128)),
                ('fb_access_token_expires', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number_token', models.CharField(blank=True, max_length=50, null=True)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='spotter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spotter.Spotter'),
        ),
    ]
